name: Build installers

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-pc-windows-msvc
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Tauri CLI
        run: npm install
      - name: Build (MSI)
        run: npm run build
      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: windows-installers
          path: src-tauri/target/release/bundle/msi/*.msi

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Tauri CLI
        run: npm install
      - name: Build (DMG)
        run: npm run build
      - name: Upload DMG and app bundle
        uses: actions/upload-artifact@v4
        with:
          name: macos-installers
          path: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/macos/*.app
